CREATE DATABASE IF NOT EXISTS ditona_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ditona_db;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS home_media (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(190) NOT NULL,
  subtitle TEXT,
  media_type ENUM('image', 'video') NOT NULL DEFAULT 'image',
  media_url TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS machines (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  category VARCHAR(120) NOT NULL,
  price INT UNSIGNED NULL,
  status VARCHAR(80),
  image_url TEXT,
  description TEXT,
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS realisations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(190) NOT NULL,
  price INT UNSIGNED NULL,
  image_url TEXT,
  comment TEXT,
  rating TINYINT UNSIGNED NOT NULL DEFAULT 5,
  client_review TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(190) NOT NULL,
  image_url TEXT,
  body TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointments (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  phone VARCHAR(80) NOT NULL,
  email VARCHAR(190),
  requested_date DATE NOT NULL,
  subject VARCHAR(190),
  message TEXT NOT NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Nouveau',
  admin_reply TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  machine_id INT UNSIGNED NULL,
  machine_name VARCHAR(190) NOT NULL,
  client_name VARCHAR(190),
  phone VARCHAR(80),
  note TEXT,
  status VARCHAR(80) NOT NULL DEFAULT 'Nouvelle',
  admin_reply TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(190) NOT NULL DEFAULT 'Visiteur web',
  email VARCHAR(190),
  phone VARCHAR(80),
  subject VARCHAR(190) NOT NULL,
  message TEXT NOT NULL,
  auto_reply TEXT,
  admin_reply TEXT,
  status VARCHAR(80) NOT NULL DEFAULT 'Nouveau',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
